### PR TITLE
Added a Raw File Upload method

### PR DESCRIPTION
**Pull request by Lioncat2002**
## Description
I noticed that currently if I want to upload a file, it needs to be first saved to disk and then uploaded to catbox
So, I added a new method which allows one to directly upload a ByteSlice. 
I Have written a test and it seems to be passing

### CODE REVIEW

**Comment by waybackarchiver** [comment]
@Lioncat2002 Thank you for your works!

Maybe we should use an `Upload` method like the following to keep the code clean. What do you think?

```diff
diff --git a/catbox.go b/catbox.go
index af9b4e4..dc317ed 100644
--- a/catbox.go
+++ b/catbox.go
@@ -16,7 +16,6 @@ import (
 	"path/filepath"
 	"time"
 
-	"github.com/pkg/errors"
 	"github.com/wabarc/helper"
 )
 
@@ -42,23 +41,39 @@ func New(client *http.Client) *Catbox {
 }
 
 // Upload file or URI to the Catbox. It returns an URL string and error.
-func (cat *Catbox) Upload(path string) (string, error) {
-	parse := func(s string, _ error) (string, error) {
-		uri, err := url.Parse(s)
-		if err != nil {
-			return "", err
-		}
-		return uri.String(), nil
+func (cat *Catbox) Upload(v ...interface{}) (string, error) {
+	if len(v) == 0 {
+		return "", fmt.Errorf(`must specify file path or byte slice`)
 	}
 
-	switch {
-	case helper.IsURL(path):
-		return parse(cat.urlUpload(path))
-	case helper.Exists(path):
-		return parse(cat.fileUpload(path))
-	default:
-		return "", errors.New(`path invalid`)
+	switch t := v[0].(type) {
+	case string:
+		path := t
+		parse := func(s string, _ error) (string, error) {
+			uri, err := url.Parse(s)
+			if err != nil {
+				return "", err
+			}
+			return uri.String(), nil
+		}
+
+		switch {
+		case helper.IsURL(path):
+			return parse(cat.urlUpload(path))
+		case helper.Exists(path):
+			return parse(cat.fileUpload(path))
+		default:
+			return "", fmt.Errorf(`path invalid`)
+		}
+	case []byte:
+		if len(v) != 2 {
+			return "", fmt.Errorf(`must specify file name`)
+		}
+		// return cat.rawUpload(v[0].([]byte), v[1].(string))
 	}
+
+	return "", fmt.Errorf(`unhandled`)
 }
```

**Comment by Lioncat2002** [comment]
@waybackarchiver  aahhh yess it will be pretty good!
I am kinda new to go so haven't got much experience with all the features 😅

I will make the change

**Comment by Lioncat2002** [comment]
done

**Comment by waybackarchiver** [comment]
LGTM

**Pull request merged**
